//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int ID { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankBranchCity { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string RoleId { get; set; }
    }
}
