//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccountType
    {
        public int ChartOfAccountTypeID { get; set; }
        public string AccountType { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string TransType { get; set; }
    }
}
