//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitAndLoss
    {
        public int ID { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string RecordType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
