//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLine
    {
        public int PurchaseOrderLineID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> SubItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> T_O { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SOLineID { get; set; }
    }
}
