//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubItem
    {
        public int SubItemID { get; set; }
        public string RoleID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string SubItemName { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> RPCharges { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public Nullable<int> OpeningInventoryId { get; set; }
        public Nullable<int> OpeningInventoryQty { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsScrap { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> PicesPerCorton { get; set; }
    }
}
