//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_ProfitLossGrossProfit
    {
        public int SaleOrderID { get; set; }
        public Nullable<System.DateTime> SoDate { get; set; }
        public string RoleID { get; set; }
        public Nullable<decimal> Dis { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
