//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DetailLedgerStatement
    {
        public Nullable<int> AccountId { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> InQty { get; set; }
        public Nullable<int> OutQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public string Remarks { get; set; }
        public int RecordId { get; set; }
        public string RoleID { get; set; }
    }
}
