//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DailyCashTransactions
    {
        public int TransID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string ChartOfAccountName { get; set; }
        public string Particular { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> DR { get; set; }
        public Nullable<decimal> CR { get; set; }
        public string RoleID { get; set; }
    }
}
