//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetCustomerAllTableInfo
    {
        public Nullable<int> RecordID { get; set; }
        public int CustomerID { get; set; }
        public string RecordType { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CityAreaID { get; set; }
        public string CityAreaName { get; set; }
        public string SalesOfficer { get; set; }
    }
}
