//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvertoryOnHandAllTypes
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public int SubItemID { get; set; }
        public string SubItemName { get; set; }
        public int InventoryID { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string RoleID { get; set; }
        public int RecordID { get; set; }
        public string RecordType { get; set; }
        public int OrderID { get; set; }
        public int DeailID { get; set; }
    }
}
