//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payments
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CheckNumberOrOnlineReciptNumber { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Particulars { get; set; }
        public string VoucherType { get; set; }
        public string RecordType { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> BankID { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> PaymentHeaderID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
    }
}
