//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaymentDetailForHeader
    {
        public int PaymentHeaderID { get; set; }
        public string PaymentDetail { get; set; }
    }
}
