//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseOrder
    {
        public int PurchaseOrderID { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int PONumber { get; set; }
        public string RecordType { get; set; }
        public int EntryTypeID { get; set; }
        public string EntryType { get; set; }
        public int AccountID { get; set; }
        public string VendorName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public string InvoiceNo { get; set; }
        public string Notes { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Expense { get; set; }
        public decimal Discount { get; set; }
        public decimal SalesTax { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Status { get; set; }
        public decimal TotalPurchasePrice { get; set; }
        public int TotalQty { get; set; }
        public decimal TotalSubTotal { get; set; }
        public bool IsTaxInvoice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VendorCNIC { get; set; }
        public string VendorAddress { get; set; }
        public string VendorSTR { get; set; }
        public string VendorNTN { get; set; }
        public string VendorCityArea { get; set; }
        public int BookerID { get; set; }
        public string BookerName { get; set; }
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
    }
}
