//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HassanAyoubTraders.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaymentHeader
    {
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReceiptNo { get; set; }
        public int EmployeeId { get; set; }
        public string SalesOfficer { get; set; }
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public string OfficerAddress { get; set; }
        public string STRN { get; set; }
        public string NTN { get; set; }
        public string CityAreaName { get; set; }
        public decimal TotalAmount { get; set; }
        public string Particular { get; set; }
        public string VoucharType { get; set; }
        public string PaymentDetail { get; set; }
    }
}
